name: "PNPM Install"
description: "Install dependencies with pnpm"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v6
      env:
        NODE_VERSION: "24"
        package-manager-cache: false # mangaged in a custom way
      with:
        node-version: "${{ env.NODE_VERSION }}"
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      id: pnpm-install
      with:
        run_install: false
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
    - name: Setup pnpm cache
      uses: actions/cache@v5
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ env.NODE_VERSION }}-${{ hashFiles('./pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-${{ env.NODE_VERSION }}-
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
