name: Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
        with:
          target: 'frontend'
      - name: Build docs
        run: pnpm build
        working-directory: frontend
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'frontend/build/'

  deploy_docs:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
